language: go

go:
  - 1.3
  - 1.6
  - tip

sudo: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get golang.org/x/text/unicode/rangetable
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert
  - go get github.com/neurosnap/sentences

script:
  - bash run_tests.sh
  - goveralls -coverprofile=coverage.out -service travis-ci

