language: go

go:
  - 1.3
  - 1.6
  - tip

sudo: false

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

before_install:
  - go get golang.org/x/text/unicode/rangetable
  - go get github.com/mattn/goveralls
  - go get github.com/stretchr/testify/assert

script:
  - go test -coverprofile=core.cover.out -covermode=count ./core
  - go test -coverprofile=tokenize.cover.out -covermode=count ./tokenize
  - echo "mode: set" > coverage.out && cat *.cover.out | grep -v mode: | sort -r | awk '{if($1 != last) {print $0;last=$1}}' >> coverage.out
  - goveralls -coverprofile=coverage.out -service travis-ci

